          players = {
              "k-mbappe.jpg": "231388.png",
              "j-bellingham.jpg": "291281.png",
              "vinicius-jr.jpg": "252107.png",
              "v-van-dijk.jpg": "157892.png",
              "j-musiala.jpg": "4397459.png",      # Updated Active ID
              "a-hakimi.jpg": "406612.png",        # Updated Active ID
              "c-pulisic.jpg": "225607.png",
              "l-lozano.jpg": "206563.png",
              "a-davies.jpg": "406653.png",        # Updated Active ID
              "l-diaz.jpg": "275014.png",
              "l-modric.jpg": "45843.png",
              "g-xhaka.jpg": "149981.png",
              "s-mane.jpg": "156080.png",
              "son-heung-min.jpg": "149945.png",
              "e-haaland.jpg": "3910604.png",      # Updated Active ID
              "h-calhanoglu.jpg": "194513.png",
              "k-de-bruyne.jpg": "134947.png",
              "d-alaba.jpg": "149303.png",
              "a-robertson.jpg": "193571.png",
              "t-mitoma.jpg": "4430841.png",       # Updated Active ID
              "d-nunez.jpg": "4231682.png",        # Updated Active ID
              "e-valencia.jpg": "74895.png",
              "l-yamal.jpg": "5174092.png",        # Updated Active ID
              "pedri.jpg": "4329241.png"           # Updated Active ID
          }
